apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:17.4-alpine3.21
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kube-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: kube-secret
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: kube-secret
                key: POSTGRES_DB


---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: vinny6202/kube_news:v1
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: kube-secret

---

apiVersion: v1
kind: Service
metadata:
  name: kube-app
spec:
  selector:
    app: kubenews
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
